const HTTP_BAD_REQUEST = 400;
const HTTP_INTERNAL_SERVER_ERROR = 500;
const OK = 200;
const Conflict = 409;
const HTTP_STATUS_FORBIDDEN = 403;
const MONGO_DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  HTTP_BAD_REQUEST,
  HTTP_INTERNAL_SERVER_ERROR,
  OK,
  Conflict,
  HTTP_STATUS_FORBIDDEN,
  MONGO_DUPLICATE_ERROR_CODE,
};
